name: Publish Docker image

on:
  schedule:
    - cron: '0 3 * * 5'
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  push_to_registries:
    name: Push Docker image to github registry
    runs-on: [self-hosted, podman]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build image
        run: podman build -t art-of-rally-leaderboard-website .

      - name: Publish image
        run: podman push art-of-rally-leaderboard-website j3sb/art-of-rally-leaderboard-website